[package]
name = "passkeys-demo"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
axum = { version = "0.8", default-features = true, features = ['json'] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
sha2 = "0.11.0"
base64 = "0.23.1"
uuid = { version = "1.26.1", features = ["v4"] }
url = "2.5.8"
email_address = "0.2.9"
hex = "0.4.3"
reqwest = { version = "0.13.5", features = ["json"] }
serde_json = "1.0.151"
chrono = "0.4.45"
bitflags = "2.13.2"
jsonwebtoken = { version = "11.1.0", features = ["rust_crypto"] }
time = "0.3.55"
md5 = "0.8.1"
urlencoding = "2.1.3"
webauthn-rs-core = "0.5.5"
openssl = "0.10.81"
serde_cbor_2 = "0.13.0"

[dev-dependencies]
rstest = "0.27.0"
