[package]
name = "passkeys-demo"
version = "1.0.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", default-features = true, features = ['json'] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
sha2 = "0.11.0"
base64 = "0.23.1"
uuid = { version = "1.26.1", features = ["v4"] }
pem = "4.0.0"
url = "2.5.8"
email_address = "0.2.9"
hex = "0.4.3"

[dev-dependencies]
rstest = "0.27.0"
